import type { Metadata } from "next";
import { Geist, Geist_Mono, Syne, Inter, Playfair_Display } from "next/font/google";
import "./globals.css";


const syne = Syne({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // pick whichever weights you need
  variable: "--font-syne", // optional, lets you use it as a CSS variable too
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Admin Cabana Wear",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${syne.className} ${inter.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">   
      {children}
      </body>
    </html>
  );
}
